---
title: Elm Town
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
excerpt_separator: ''
plugins:
  - jekyll-paginate
highlighter: pygments
markdown: kramdown
url: http://elmtown.github.io
email: 
author: Murphy Randle
description: A podcast about Elm and its people
paginate: 50
google_analytics: 
